# Generated by Django 5.0.4 on 2024-12-24 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SubjectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('specialization', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Break',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='table.day')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='table.department')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='major_subjects',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='major_departments', to='table.subjectgroup'),
        ),
        migrations.AddField(
            model_name='department',
            name='minor_subjects',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minor_departments', to='table.subjectgroup'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('Major', 'Major'), ('Minor', 'Minor')], max_length=10)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='table.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectGroupMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='table.subjectgroup')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='table.subject')),
            ],
            options={
                'unique_together': {('group', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(blank=True, max_length=20, null=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='table.day')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='table.department')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='table.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='table.teacher')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='table.timeslot')),
            ],
            options={
                'unique_together': {('day', 'time_slot', 'department'), ('day', 'time_slot', 'teacher')},
            },
        ),
    ]
