# Generated by Django 5.1.4 on 2025-01-05 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='department',
            name='semester',
            field=models.CharField(choices=[('1st Semester', '1st Semester'), ('2nd Semester', '2nd Semester'), ('3rd Semester', '3rd Semester'), ('4th Semester', '4th Semester'), ('5th Semester', '5th Semester'), ('6th Semester', '6th Semester'), ('7th Semester', '7th Semester'), ('8th Semester', '8th Semester')], default='1st semister', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='available_time_slots',
            field=models.ManyToManyField(related_name='available_teachers', to='table.timeslot'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='semester',
            field=models.CharField(choices=[('1st Semester', '1st Semester'), ('2nd Semester', '2nd Semester'), ('3rd Semester', '3rd Semester'), ('4th Semester', '4th Semester'), ('5th Semester', '5th Semester'), ('6th Semester', '6th Semester'), ('7th Semester', '7th Semester'), ('8th Semester', '8th Semester')], default='1st semister', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='end_time',
            field=models.CharField(choices=[('8:30 - 9:30', '8:30 - 9:30'), ('9:30 - 10:30', '9:30 - 10:30'), ('11:00 - 12:00', '11:00 - 12:00'), ('12:00 - 1:00', '12:00 - 1:00'), ('1:00 - 2:00', '1:00 - 2:00'), ('2:00 - 3:00', '2:00 - 3:00'), ('3:00 - 4:00', '3:00 - 4:00'), ('4:00 - 5:00', '4:00 - 5:00')], default='1:00 - 2:00', max_length=20),
        ),
        migrations.AlterField(
            model_name='department',
            name='start_time',
            field=models.CharField(choices=[('8:30 - 9:30', '8:30 - 9:30'), ('9:30 - 10:30', '9:30 - 10:30'), ('11:00 - 12:00', '11:00 - 12:00'), ('12:00 - 1:00', '12:00 - 1:00'), ('1:00 - 2:00', '1:00 - 2:00'), ('2:00 - 3:00', '2:00 - 3:00'), ('3:00 - 4:00', '3:00 - 4:00'), ('4:00 - 5:00', '4:00 - 5:00')], default='8:30 - 9:30', max_length=20),
        ),
        migrations.AlterField(
            model_name='department',
            name='year',
            field=models.CharField(choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year'), ('Final Year', 'Final Year')], max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='working_hours',
            field=models.CharField(choices=[('8:30 - 9:30', '8:30 - 9:30'), ('9:30 - 10:30', '9:30 - 10:30'), ('11:00 - 12:00', '11:00 - 12:00'), ('12:00 - 1:00', '12:00 - 1:00'), ('1:00 - 2:00', '1:00 - 2:00'), ('2:00 - 3:00', '2:00 - 3:00'), ('3:00 - 4:00', '3:00 - 4:00'), ('4:00 - 5:00', '4:00 - 5:00')], max_length=20),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_time',
            field=models.CharField(choices=[('8:30 - 9:30', '8:30 - 9:30'), ('9:30 - 10:30', '9:30 - 10:30'), ('11:00 - 12:00', '11:00 - 12:00'), ('12:00 - 1:00', '12:00 - 1:00'), ('1:00 - 2:00', '1:00 - 2:00'), ('2:00 - 3:00', '2:00 - 3:00'), ('3:00 - 4:00', '3:00 - 4:00'), ('4:00 - 5:00', '4:00 - 5:00')], default='1:00 - 2:00', max_length=20),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='start_time',
            field=models.CharField(choices=[('8:30 - 9:30', '8:30 - 9:30'), ('9:30 - 10:30', '9:30 - 10:30'), ('11:00 - 12:00', '11:00 - 12:00'), ('12:00 - 1:00', '12:00 - 1:00'), ('1:00 - 2:00', '1:00 - 2:00'), ('2:00 - 3:00', '2:00 - 3:00'), ('3:00 - 4:00', '3:00 - 4:00'), ('4:00 - 5:00', '4:00 - 5:00')], default='8:30 - 9:30', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('department', 'subject', 'timeslot', 'year_group', 'semester')},
        ),
    ]
